using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Database.Migrations
{
    /// <inheritdoc />
    public partial class DeferDeleteChecksForEntitiesThatCanOnlyBeDeletedTogether : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongsid\"() CASCADE;");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() RETURNS trigger as $LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$\r\nBEGIN\r\n  IF (\n    (OLD.\"CalorimetricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"calorimetric_data\"\n    WHERE \"Id\" = OLD.\"CalorimetricDataId\"\n)) OR (OLD.\"GeometricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"geometric_data\"\n    WHERE \"Id\" = OLD.\"GeometricDataId\"\n)) OR (OLD.\"HygrothermalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"hygrothermal_data\"\n    WHERE \"Id\" = OLD.\"HygrothermalDataId\"\n)) OR (OLD.\"LifeCycleDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"lifeCycle_data\"\n    WHERE \"Id\" = OLD.\"LifeCycleDataId\"\n)) OR (OLD.\"OpticalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"optical_data\"\n    WHERE \"Id\" = OLD.\"OpticalDataId\"\n)) OR (OLD.\"PhotovoltaicDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"photovoltaic_data\"\n    WHERE \"Id\" = OLD.\"PhotovoltaicDataId\"\n))\n) THEN\n    RAISE EXCEPTION 'You cannot delete a data access policy without also deleting the corresponding data in the same transaction.';\nEND IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data AFTER DELETE\r\nON \"database\".\"data_access_policy\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_resource_root_can_only_deleted_alongside_its_data\"() RETURNS trigger as $LC_TRIGGER_resource_root_can_only_deleted_alongside_its_data$\r\nBEGIN\r\n  IF OLD.\"ParentId\" IS NULL AND (\n    (OLD.\"CalorimetricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"calorimetric_data\" \n    WHERE \"Id\" = OLD.\"CalorimetricDataId\"\n)) OR (OLD.\"GeometricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"geometric_data\" \n    WHERE \"Id\" = OLD.\"GeometricDataId\"\n)) OR (OLD.\"HygrothermalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"hygrothermal_data\" \n    WHERE \"Id\" = OLD.\"HygrothermalDataId\"\n)) OR (OLD.\"LifeCycleDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"lifeCycle_data\" \n    WHERE \"Id\" = OLD.\"LifeCycleDataId\"\n)) OR (OLD.\"OpticalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"optical_data\" \n    WHERE \"Id\" = OLD.\"OpticalDataId\"\n)) OR (OLD.\"PhotovoltaicDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"photovoltaic_data\" \n    WHERE \"Id\" = OLD.\"PhotovoltaicDataId\"\n))\n) THEN\n    RAISE EXCEPTION 'You cannot delete a root resource without also deleting the corresponding data in the same transaction.';\nEND IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_resource_root_can_only_deleted_alongside_its_data$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_resource_root_can_only_deleted_alongside_its_data AFTER DELETE\r\nON \"database\".\"get_https_resource\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_resource_root_can_only_deleted_alongside_its_data\"();");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_resource_root_can_only_deleted_alongside_its_data\"() CASCADE;");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() RETURNS trigger as $LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$\r\nBEGIN\r\n  IF (\n    (OLD.\"CalorimetricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"calorimetric_data\"\n    WHERE \"Id\" = OLD.\"CalorimetricDataId\"\n)) OR (OLD.\"GeometricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"geometric_data\"\n    WHERE \"Id\" = OLD.\"GeometricDataId\"\n)) OR (OLD.\"HygrothermalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"hygrothermal_data\"\n    WHERE \"Id\" = OLD.\"HygrothermalDataId\"\n)) OR (OLD.\"LifeCycleDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"lifeCycle_data\"\n    WHERE \"Id\" = OLD.\"LifeCycleDataId\"\n)) OR (OLD.\"OpticalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"optical_data\"\n    WHERE \"Id\" = OLD.\"OpticalDataId\"\n)) OR (OLD.\"PhotovoltaicDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"photovoltaic_data\"\n    WHERE \"Id\" = OLD.\"PhotovoltaicDataId\"\n))\n) THEN\n    RAISE EXCEPTION 'You cannot delete a data access policy without also deleting the corresponding data in the same transaction.';\nEND IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data BEFORE DELETE\r\nON \"database\".\"data_access_policy\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongsid\"() RETURNS trigger as $LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongsid$\r\nBEGIN\r\n  IF OLD.\"ParentId\" IS NULL AND (\n    (OLD.\"CalorimetricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"calorimetric_data\" \n    WHERE \"Id\" = OLD.\"CalorimetricDataId\"\n)) OR (OLD.\"GeometricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"geometric_data\" \n    WHERE \"Id\" = OLD.\"GeometricDataId\"\n)) OR (OLD.\"HygrothermalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"hygrothermal_data\" \n    WHERE \"Id\" = OLD.\"HygrothermalDataId\"\n)) OR (OLD.\"LifeCycleDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"lifeCycle_data\" \n    WHERE \"Id\" = OLD.\"LifeCycleDataId\"\n)) OR (OLD.\"OpticalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"optical_data\" \n    WHERE \"Id\" = OLD.\"OpticalDataId\"\n)) OR (OLD.\"PhotovoltaicDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"photovoltaic_data\" \n    WHERE \"Id\" = OLD.\"PhotovoltaicDataId\"\n))\n) THEN\n    RAISE EXCEPTION 'You cannot delete a root resource without also deleting the corresponding data in the same transaction.';\nEND IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongsid$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongsid BEFORE DELETE\r\nON \"database\".\"get_https_resource\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongsid\"();");
        }
    }
}